### ISSUE TITLE
C++ -like STL?

### ISSUE THREAD

**Issue by CsatiZoltan** [davidvarga/MXtension#1]
For a while I was thinking of porting certain aspects of the STL in C++ to MATLAB, i.e. creating containers with associated operations on them. Is this or something similar have in your future plans? If so, I won't implement them by myself.

**Comment by davidvarga** [comment]
It's like the Collections package from Java, but with extensions from functional languages and mutability and immutability.

For example a mutable list from this project will look like really similarily as a MutableList in Kotlin: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-mutable-list/index.html

**Comment by CsatiZoltan** [comment]
Ok, so the idea is similar.
